export class Local {
    static en() {
        return {
            'New password info': 'New password info',
            'Show actual version': 'Show actual version',
            'Show/Hide password': 'Show/Hide password',
            'Generate new password': 'Generate new password',
            'Open in default browser': 'Open in default browser',
            'Copy to clipboard': 'Copy to clipboard',
            'Clipboard': 'Clipboard',
            'copied to clipboard': 'copied to clipboard',
            'Password by': 'Password by',
            'Login by': 'Login by',
            'Remove item': 'Remove item',
            Password: 'Password',
            Search: 'Search',
            Add: 'Add',
            Load: 'Load',
            Save: 'Save',
            Certificates: 'Certificates',
            'Public key': 'Public key',
            'Private key': 'Private key',
            'Create certificate': 'Create certificate',
            'Password cards': 'Password cards',
            Comment: 'Comment',
            Login: 'Login',
            Site: 'Site',
            Resource: 'Resource',
        }
    }

    static ru() {
        return {
            'New password info': 'Новая информация',
            'Show actual version': 'Посмотреть актуальную версию',
            'Show/Hide password': 'Показать/Скрыть пароль',
            'Generate new password': 'Генерация нового пароля',
            'Open in default browser': 'Открыть сайт в браузере',
            'Clipboard': 'Буфер обмена',
            'Copy to clipboard': 'Копировать в буфер',
            'copied to clipboard': 'скопирован в буфер',
            'Password by': 'Пароль',
            'Login by': 'Логин',
            'Remove item': 'Удалить',
            Password: 'Пароль',
            Search: 'Поиск',
            Add: 'Добавить',
            Load: 'Загрузить',
            Save: 'Сохранить',
            Certificates: 'Сертификаты',
            'Public key': 'Публичный ключ',
            'Private key': 'Приватный ключ',
            'Create certificate': 'Создать сертификат',
            'Password cards': 'Карточки ресурсов',
            Comment: 'Коментарий',
            Login: 'Логин',
            Site: 'Сайт',
            Resource: 'Ресурс',
        }
    }
}
